#!/usr/bin/env python
"""
Startup script for SageMaker inference server.
Starts nginx and gunicorn to serve the Flask application.
"""
import multiprocessing
import os
import signal
import subprocess
import sys

# Number of worker processes
cpu_count = multiprocessing.cpu_count()
model_server_timeout = os.environ.get('MODEL_SERVER_TIMEOUT', 60)
model_server_workers = int(os.environ.get('MODEL_SERVER_WORKERS', cpu_count))


def sigterm_handler(nginx_pid, gunicorn_pid):
    """Handle SIGTERM signal"""
    try:
        os.kill(nginx_pid, signal.SIGQUIT)
    except OSError:
        pass
    try:
        os.kill(gunicorn_pid, signal.SIGTERM)
    except OSError:
        pass
    sys.exit(0)


def start_server():
    """Start the inference server"""
    print('Starting the inference server with {} workers.'.format(model_server_workers))
    
    # Link nginx log files to stdout/stderr
    subprocess.check_call(['ln', '-sf', '/dev/stdout', '/var/log/nginx/access.log'])
    subprocess.check_call(['ln', '-sf', '/dev/stderr', '/var/log/nginx/error.log'])
    
    # Start nginx
    nginx = subprocess.Popen(['nginx', '-c', '/opt/program/nginx.conf'])
    
    # Start gunicorn
    gunicorn = subprocess.Popen([
        'gunicorn',
        '--timeout', str(model_server_timeout),
        '-k', 'sync',
        '-b', 'unix:/tmp/gunicorn.sock',
        '-w', str(model_server_workers),
        'wsgi:app'
    ])
    
    # Setup signal handler
    signal.signal(signal.SIGTERM, lambda a, b: sigterm_handler(nginx.pid, gunicorn.pid))
    
    # Wait for child processes
    pids = {nginx.pid, gunicorn.pid}
    while True:
        pid, _ = os.wait()
        if pid in pids:
            break
    
    # Cleanup
    sigterm_handler(nginx.pid, gunicorn.pid)
    print('Inference server exiting')


if __name__ == '__main__':
    start_server()
